### ISSUE TITLE
NPE when adding connections

### ISSUE THREAD

**Issue by coolya** [slisson/mps-diagram-editor#133]
With MPS3.2 adding new component port connection on mebddr components failes with a NPE. Using git revision baf143e,

Synchronisation to the MPS model failed
java.lang.NullPointerException
	at jetbrains.mps.nodeEditor.EditorContext.createNodeCell(EditorContext.java:189)
	at de.itemis.mps.editor.diagram.runtime.model.AccessorFactory.fromSNode(AccessorFactory.java:35)
	at de.itemis.mps.editor.diagram.runtime.model.AccessorFactory.edgeFromSNode(AccessorFactory.java:52)
	at com.mbeddr.ext.components.editor.InstanceConfiguration_graphicalWiring_Editor$2$1$1$2.create(InstanceConfiguration_graphicalWiring_Editor.java:202)
	at de.itemis.mps.editor.diagram.runtime.model.SNodeConnectionType.create(SNodeConnectionType.java:34)
	at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer.toSModel_(ModelSynchronizer.java:113)
	at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer$1.run(ModelSynchronizer.java:56)
	at jetbrains.mps.editor.runtime.commands.EditorCommandAdapter.doExecute(EditorCommandAdapter.java:46)
	at jetbrains.mps.editor.runtime.commands.EditorCommand.run(EditorCommand.java:46)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess$CommandRunnable$1.run(WorkbenchModelAccess.java:705)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess.runWriteAction(WorkbenchModelAccess.java:142)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess$CommandRunnable.run(WorkbenchModelAccess.java:700)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:117)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess.runWriteActionInCommand(WorkbenchModelAccess.java:539)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess.executeCommand(WorkbenchModelAccess.java:502)
	at jetbrains.mps.project.ProjectModelAccess.executeCommand(ProjectModelAccess.java:36)
	at jetbrains.mps.nodeEditor.EditorComponent.executeCommand(EditorComponent.java:2441)
	at jetbrains.mps.nodeEditor.EditorContext.executeCommand(EditorContext.java:360)
	at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer.toSModel(ModelSynchronizer.java:54)
	at de.itemis.mps.editor.diagram.runtime.model.DiagramModel.synchronizeWrite(DiagramModel.java:168)
	at de.itemis.mps.editor.diagram.runtime.jgraph.JGraphModelSynchronizer$3$1.run(JGraphModelSynchronizer.java:125)
	at jetbrains.mps.editor.runtime.commands.EditorCommandAdapter.doExecute(EditorCommandAdapter.java:46)
	at jetbrains.mps.editor.runtime.commands.EditorCommand.run(EditorCommand.java:46)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess$CommandRunnable$1.run(WorkbenchModelAccess.java:705)
	at jetbrains.mps.smodel.WriteActionDispatcher.run(WriteActionDispatcher.java:39)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess$3.run(WorkbenchModelAccess.java:155)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:974)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess.runWriteAction(WorkbenchModelAccess.java:164)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess$CommandRunnable.run(WorkbenchModelAccess.java:700)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess.runWriteActionInCommand(WorkbenchModelAccess.java:539)
	at jetbrains.mps.ide.smodel.WorkbenchModelAccess.executeCommand(WorkbenchModelAccess.java:502)
	at jetbrains.mps.project.ProjectModelAccess.executeCommand(ProjectModelAccess.java:36)
	at jetbrains.mps.nodeEditor.EditorComponent.executeCommand(EditorComponent.java:2441)
	at jetbrains.mps.nodeEditor.EditorContext.executeCommand(EditorContext.java:360)
	at de.itemis.mps.editor.diagram.runtime.jgraph.JGraphModelSynchronizer$3.invoke(JGraphModelSynchronizer.java:122)
	at com.mxgraph.util.mxEventSource.fireEvent(mxEventSource.java:179)
	at com.mxgraph.util.mxEventSource.fireEvent(mxEventSource.java:151)
	at com.mxgraph.model.mxGraphModel.endUpdate(mxGraphModel.java:1100)
	at com.mxgraph.swing.handler.mxConnectionHandler.mouseReleased(mxConnectionHandler.java:763)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
	at de.itemis.mps.editor.diagram.runtime.jgraph.MyGraphComponent$MyGraphControl.processMouseEvent(MyGraphComponent.java:260)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by coolya** [comment]
Seems like this a mbeddr problem. That mebddr is passing null as the node which should be the edge. Investigating.

**Comment by slisson** [comment]
I found the reason. It's not an mbeddr problem.
